### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Irvingzr16#1]
[Mapa Mental ME.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Irvingzr16/files/14671521/Mapa.Mental.ME.pdf)

**Comment by Luz1727** [comment]
20/20

**Comment by josealfredo79** [comment]
@Irvingzr16 Hace falta mas informacion de la Web 3.0....hay que evaluar mas objetivo por favor.. @Luz1727

**Comment by Irvingzr16** [comment]
X somos chavos!
